CREATE TABLE accounts(
  id VARCHAR(255) NOT NULL PRIMARY KEY COMMENT 'primary key',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  name VARCHAR(255) NOT NULL COMMENT 'Users given name',
  email VARCHAR(255) NOT NULL COMMENT 'Auth Email',
  picture VARCHAR(255) NOT NULL COMMENT 'Picture URL',
) DEFAULT charset utf8 COMMENT '';
